### ISSUE TITLE
Offset output channel 

### ISSUE THREAD

**Issue by zhujiagang** [lshiwjx/deform_conv3d_pytorch_op#2]
https://github.com/lshiwjx/deform_conv3d_pytorch_op/blob/03985c6d7653dacb3466c99886b307ec6683f71d/deform2d_double/test_model.py#L22 Your implementation is not the same as the original paper described in section 2.1. Offset output channel dimension should be 2 x N, where N is the conv kernel size k*k in 2D case. That is, the offset is shared across the channel dimension. You could refer to the implementation of [https://github.com/ChunhuanLin/deform_conv_pytorch](url)

**Comment by lshiwjx** [comment]
If you set the channel_per_group the same as c_in, it will be your case.
You could refer to the official implementation:  https://github.com/msracver/Deformable-ConvNets/blob/a2977507d0980bafab7e4161ea78138fe510cb65/rfcn/operator_cxx/nn/deformable_im2col.cuh#L232
