### ISSUE TITLE
关于可变形卷积的理解

### ISSUE THREAD

**Issue by mathxiaobin** [lshiwjx/deform_conv3d_pytorch_op#3]
我想问一个问题：可形变卷积在具体实现的过程中，并不是像文章中描述的那样，去按照学到的形变去提取对应点的数值去运算。而是将对应点的数值通过差值放到标准卷积对应为的下方，然后再用标准卷积去运算？也就是说对feature map先做一个变换，然后再卷积?

**Comment by lshiwjx** [comment]
不好意思才看到，卷积在实现的过程中是将原数据变换为两个矩阵再相乘。可变形卷积是改变了从原数据到矩阵的这个过程。
